services:
  pdf-service:
    image: registry-irk-rw.devops.rgf.local/gimmyhat/pdf-service-go:${VERSION:-latest}
    ports:
      - "8080:8080"
    volumes:
      - ./internal/domain/pdf/templates:/app/internal/domain/pdf/templates
      - pdf_stats:/app/data
    environment:
      - GIN_MODE=release
      - GOTENBERG_URL=http://gotenberg:3000
      - GOTENBERG_CLIENT_TIMEOUT=60s
      - LOG_LEVEL=debug
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pdf_service
      - POSTGRES_USER=pdf_service
      - POSTGRES_PASSWORD=pdf_service
      # OpenTelemetry конфигурация
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
      - OTEL_SERVICE_NAME=pdf-service
      - OTEL_SERVICE_VERSION=${VERSION:-latest}
      - OTEL_ENVIRONMENT=development
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_TIMEOUT=30s
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=1.0
      - OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT=4096
      - OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT=128
      - OTEL_SPAN_EVENT_COUNT_LIMIT=128
      - OTEL_SPAN_LINK_COUNT_LIMIT=128
      - OTEL_BATCH_TIMEOUT=5
      - OTEL_MAX_EXPORT_BATCH_SIZE=512
      - OTEL_MAX_QUEUE_SIZE=2048
      - OTEL_LOG_LEVEL=info
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development,service.namespace=local
      - OTEL_PROPAGATORS=tracecontext,baggage,jaeger
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_METRIC_EXPORT_INTERVAL=30000
    depends_on:
      postgres:
        condition: service_healthy
      gotenberg:
        condition: service_started
      jaeger:
        condition: service_started

  gotenberg:
    image: registry-irk-rw.devops.rgf.local/gotenberg/gotenberg:7.10
    ports:
      - "3000:3000"
    environment:
      - GOTENBERG_MAX_WORKERS=4
      - GOTENBERG_CHROMIUM_MAX_QUEUE_SIZE=10
      - GOTENBERG_LIBREOFFICE_MAX_QUEUE_SIZE=10
      - GOTENBERG_DEFAULT_WAIT_TIMEOUT=60
      - GOTENBERG_DEFAULT_WAIT_DELAY=1
    command:
      - "gotenberg"
      - "--api-port=3000"
      - "--api-timeout=60s"
      - "--libreoffice-start-timeout=60s"
      - "--api-start-timeout=60s"
      - "--chromium-start-timeout=60s"
      - "--gotenberg-graceful-shutdown-duration=60s"
      - "--webhook-client-timeout=60s"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--libreoffice-restart-after=10"
      - "--api-trace-header=X-Request-ID"
      - "--log-level=info"
      - "--log-format=json"

  postgres:
    image: registry-irk-rw.devops.rgf.local/postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pdf_service
      - POSTGRES_USER=pdf_service
      - POSTGRES_PASSWORD=pdf_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pdf_service -d pdf_service"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: registry-irk-rw.devops.rgf.local/jaegertracing/all-in-one:1.47
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  pdf_stats:
  postgres_data: 