version: '3'

services:
  pdf-service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./internal/domain/pdf/templates:/app/internal/domain/pdf/templates
    environment:
      - GIN_MODE=release
      - GOTENBERG_API_URL=http://gotenberg:3000
      - LOG_LEVEL=debug
    depends_on:
      - gotenberg

  gotenberg:
    image: gotenberg/gotenberg:7.10
    ports:
      - "3000:3000"
    command:
      - "gotenberg"
      - "--api-port=3000"
      - "--api-timeout=60s"
      - "--chromium-disable-javascript" 