apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-pdf-service-config
  namespace: print-serv
data:
  GOTENBERG_API_URL: http://nas-pdf-service-gotenberg:3000
  GIN_MODE: release
  LOG_LEVEL: debug
  
  # Основные настройки трейсинга
  OTEL_EXPORTER_OTLP_ENDPOINT: nas-jaeger:4317
  OTEL_SERVICE_NAME: nas-pdf-service
  # Это значение автоматически обновляется при деплое из current_version.txt
  OTEL_SERVICE_VERSION: 25.02.09.2108
  OTEL_ENVIRONMENT: development
  
  # Настройки протокола
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_EXPORTER_OTLP_TIMEOUT: 30s
  
  # Настройки сэмплирования
  OTEL_TRACES_SAMPLER: parentbased_traceidratio
  OTEL_TRACES_SAMPLER_ARG: "1.0"
  
  # Лимиты для спанов
  OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT: "4096"
  OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT: "128"
  OTEL_SPAN_EVENT_COUNT_LIMIT: "128"
  OTEL_SPAN_LINK_COUNT_LIMIT: "128"
  
  # Настройки батчинга
  OTEL_BATCH_TIMEOUT: "5"
  OTEL_MAX_EXPORT_BATCH_SIZE: "512"
  OTEL_MAX_QUEUE_SIZE: "2048"
  
  # Настройки логирования SDK
  OTEL_LOG_LEVEL: info
  
  # Дополнительные атрибуты ресурса
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=development,service.namespace=print-serv
  
  # Настройки пропагации контекста
  OTEL_PROPAGATORS: tracecontext,baggage,jaeger
  
  # Настройки метрик
  OTEL_METRICS_EXPORTER: prometheus
  OTEL_METRIC_EXPORT_INTERVAL: "30000"
  
  # Настройки для интеграции с Kubernetes
  KUBERNETES_NAMESPACE: print-serv
  KUBERNETES_CLUSTER: development 