apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-grafana-datasources
  namespace: print-serv
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://nas-prometheus:9090
        uid: prometheus
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "5s"
          httpMethod: "POST"
        version: 1 