apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-service-hpa
  namespace: print-serv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-service
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70 