apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-pdf-service-prometheus-config
  namespace: print-serv
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/rules/*.yaml
    scrape_configs:
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - print-serv
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_service_name
      - job_name: 'gotenberg'
        static_configs:
          - targets: ['nas-pdf-service-gotenberg:3000']
        metrics_path: '/prometheus/metrics'
        scheme: http
        scrape_interval: 5s
        scrape_timeout: 5s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-pdf-service-prometheus-rules
  namespace: print-serv
data:
  circuit-breaker.yaml: |
    groups:
    - name: circuit-breaker
      rules:
      - alert: NasPdfServiceCircuitBreakerOpen
        expr: circuit_breaker_state{name="gotenberg", job="pdf-service"} == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker is Open"
          description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} has been Open for 5 minutes"
      - alert: NasPdfServiceHighCircuitBreakerFailureRate
        expr: rate(circuit_breaker_failures_total{name="gotenberg", job="pdf-service"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Circuit Breaker failure rate"
          description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} has high failure rate"
      - alert: NasPdfServiceCircuitBreakerUnhealthy
        expr: circuit_breaker_pod_health{name="gotenberg", job="pdf-service"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Circuit Breaker is Unhealthy"
          description: "Circuit Breaker health check failing for {{ $labels.name }} in pod {{ $labels.pod_name }}"
      - alert: NasPdfServiceCircuitBreakerSlowRecovery
        expr: histogram_quantile(0.95, rate(circuit_breaker_recovery_duration_seconds_bucket{name="gotenberg", job="pdf-service"}[30m])) > 300
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker slow recovery"
          description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} is taking too long to recover"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nas-pdf-service-prometheus
  namespace: print-serv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nas-pdf-service-prometheus
  template:
    metadata:
      labels:
        app: nas-pdf-service-prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: nas-pdf-service-prometheus
        image: dh-mirror.gitverse.ru/prom/prometheus:latest
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.enable-lifecycle"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: rules
          mountPath: /etc/prometheus/rules
        - name: storage
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: nas-pdf-service-prometheus-config
      - name: rules
        configMap:
          name: nas-pdf-service-prometheus-rules
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nas-pdf-service-prometheus
  namespace: print-serv
spec:
  selector:
    app: nas-pdf-service-prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: print-serv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
  namespace: print-serv
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  namespace: print-serv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: print-serv 