apiVersion: apps/v1
kind: Deployment
metadata:
  name: nas-pdf-service
  namespace: print-serv
  labels:
    app: nas-pdf-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nas-pdf-service
  template:
    metadata:
      labels:
        app: nas-pdf-service
    spec:
      containers:
      - name: nas-pdf-service
        image: gimmyhat/pdf-service-go:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MAX_CONCURRENT_REQUESTS
          value: "4"
        - name: DOCX_TEMPLATE_CACHE_TTL
          value: "5m"
        - name: DOCX_CIRCUIT_BREAKER_FAILURE_THRESHOLD
          value: "3"
        - name: DOCX_CIRCUIT_BREAKER_RESET_TIMEOUT
          value: "5s"
        - name: DOCX_CIRCUIT_BREAKER_HALF_OPEN_MAX_CALLS
          value: "2"
        - name: DOCX_CIRCUIT_BREAKER_SUCCESS_THRESHOLD
          value: "2"
        envFrom:
        - configMapRef:
            name: nas-pdf-service-config
        volumeMounts:
        - name: templates
          mountPath: /app/internal/domain/pdf/templates
        - name: tmp-storage
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "384Mi"
            cpu: "300m"
          limits:
            memory: "768Mi"
            cpu: "600m"
      volumes:
      - name: templates
        configMap:
          name: nas-pdf-service-templates
      - name: tmp-storage
        emptyDir: {} 