apiVersion: v1
kind: Service
metadata:
  name: nas-pdf-service-gotenberg
  namespace: print-serv
spec:
  selector:
    app: nas-pdf-service-gotenberg
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nas-pdf-service-gotenberg
  namespace: print-serv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nas-pdf-service-gotenberg
  template:
    metadata:
      labels:
        app: nas-pdf-service-gotenberg
    spec:
      containers:
      - name: nas-pdf-service-gotenberg
        image: dh-mirror.gitverse.ru/gotenberg/gotenberg:7.10
        args:
        - gotenberg
        - --api-port=3000
        - --chromium-disable-javascript=true
        - --chromium-allow-list=file:///tmp/.*
        - --libreoffice-restart-after=10
        - --libreoffice-start-timeout=120s
        - --api-timeout=180s
        - --api-start-timeout=120s
        - --api-trace-header=X-Request-ID
        - --log-level=info
        - --log-format=json
        - --chromium-start-timeout=60s
        - --gotenberg-graceful-shutdown-duration=60s
        - --webhook-client-timeout=60s
        ports:
        - containerPort: 3000
        env:
        - name: GOTENBERG_MAX_WORKERS
          value: "4"
        - name: GOTENBERG_LIBREOFFICE_MAX_QUEUE_SIZE
          value: "10"
        - name: GOTENBERG_CHROMIUM_MAX_QUEUE_SIZE
          value: "10"
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
          successThreshold: 1
        volumeMounts:
        - name: tmp-storage
          mountPath: /tmp
      volumes:
      - name: tmp-storage
        emptyDir:
          sizeLimit: 2Gi 