apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nas-pdf-service-alerts
  namespace: print-serv
  labels:
    app: nas-pdf-service
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: circuit-breaker
    rules:
    - alert: NasPdfServiceCircuitBreakerOpen
      expr: circuit_breaker_state{name=~"gotenberg|docx_generator", job="pdf-service"} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Circuit Breaker is Open"
        description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} has been Open for 5 minutes"
        
    - alert: NasPdfServiceHighCircuitBreakerFailureRate
      expr: rate(circuit_breaker_failures_total{name=~"gotenberg|docx_generator", job="pdf-service"}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Circuit Breaker failure rate"
        description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} has high failure rate"
        
    - alert: NasPdfServiceCircuitBreakerUnhealthy
      expr: circuit_breaker_pod_health{name=~"gotenberg|docx_generator", job="pdf-service"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Circuit Breaker is Unhealthy"
        description: "Circuit Breaker health check failing for {{ $labels.name }} in pod {{ $labels.pod_name }}"
        
    - alert: NasPdfServiceCircuitBreakerSlowRecovery
      expr: histogram_quantile(0.95, rate(circuit_breaker_recovery_duration_seconds_bucket{name=~"gotenberg|docx_generator", job="pdf-service"}[30m])) > 300
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Circuit Breaker slow recovery"
        description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} is taking too long to recover"

  - name: pdf-service.scaling
    rules:
    - alert: HighCPUUsage
      expr: avg(rate(container_cpu_usage_seconds_total{container="nas-pdf-service"}[5m])) * 100 > 60
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage on PDF Service
        description: PDF Service CPU usage is above 60% for 5 minutes

    - alert: HighMemoryUsage
      expr: avg(container_memory_usage_bytes{container="nas-pdf-service"}) / avg(container_memory_limit_bytes{container="nas-pdf-service"}) * 100 > 65
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High Memory usage on PDF Service
        description: PDF Service Memory usage is above 65% for 5 minutes

    - alert: HighErrorRate
      expr: sum(increase(pdf_generation_total{status="error"}[5m])) / sum(increase(pdf_generation_total[5m])) * 100 > 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High error rate in PDF generation
        description: PDF generation error rate is above 10% in the last 5 minutes

    - alert: ScalingLimited
      expr: kube_horizontalpodautoscaler_status_condition{condition="ScalingLimited",namespace="print-serv",status="true"} == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: HPA scaling is limited
        description: HorizontalPodAutoscaler is unable to scale further for 10 minutes

    - alert: SlowResponseTime
      expr: histogram_quantile(0.95, sum(rate(pdf_generation_duration_seconds_bucket[5m])) by (le)) > 3
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Slow PDF generation response time
        description: 95th percentile of PDF generation time is above 3 seconds for 5 minutes

    - alert: PDFServiceLowCacheHitRate
      expr: |
        sum(rate(template_cache_hits_total[5m])) /
        (sum(rate(template_cache_hits_total[5m])) + sum(rate(template_cache_misses_total[5m]))) < 0.7
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Низкий процент попаданий в кэш шаблонов"
        description: "Hit rate кэша шаблонов ниже 70% в течение 15 минут"

    - alert: PDFServiceHighCacheSize
      expr: sum(template_cache_size_bytes) > 100 * 1024 * 1024
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Большой размер кэша шаблонов"
        description: "Размер кэша шаблонов превышает 100MB"

    - alert: PDFServiceHighCacheMissRate
      expr: |
        sum(rate(template_cache_misses_total[5m])) /
        (sum(rate(template_cache_hits_total[5m])) + sum(rate(template_cache_misses_total[5m]))) > 0.4
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Высокая частота промахов кэша"
        description: "Более 40% запросов не находят шаблон в кэше"

    - alert: PDFServiceUnstableCacheSize
      expr: |
        abs(
          (sum(template_cache_size_bytes) - 
          sum(template_cache_size_bytes offset 5m)) /
          sum(template_cache_size_bytes offset 5m)
        ) > 0.3
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Нестабильный размер кэша"
        description: "Размер кэша изменяется более чем на 30% за 5 минут"

    - alert: PDFServiceCacheMemoryPressure
      expr: |
        sum(template_cache_size_bytes) / 
        sum(container_memory_working_set_bytes{container="pdf-service"}) * 100 > 40
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Высокое потребление памяти кэшем"
        description: "Кэш использует более 40% рабочей памяти сервиса"

    - alert: PDFServiceCacheEfficiencyDrop
      expr: |
        (
          sum(rate(template_cache_hits_total[30m])) /
          (sum(rate(template_cache_hits_total[30m])) + sum(rate(template_cache_misses_total[30m])))
        ) < 0.5
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Низкая эффективность кэша"
        description: "Эффективность кэша ниже 50% в течение 30 минут" 