apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-prometheus-config
  namespace: print-serv
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/rules/*.yaml
    scrape_configs:
      - job_name: 'pdf-service'
        static_configs:
          - targets: ['nas-pdf-service:8080']
        metrics_path: '/metrics'
      - job_name: 'gotenberg'
        static_configs:
          - targets: ['nas-gotenberg:3000']
        metrics_path: '/prometheus/metrics'
        scheme: http
        scrape_interval: 5s
        scrape_timeout: 5s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-prometheus-rules
  namespace: print-serv
data:
  circuit-breaker.yaml: |
    groups:
    - name: circuit-breaker
      rules:
      - alert: NasPdfServiceCircuitBreakerOpen
        expr: circuit_breaker_state{name="gotenberg", job="pdf-service"} == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker is Open"
          description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} has been Open for 5 minutes"
      - alert: NasPdfServiceHighCircuitBreakerFailureRate
        expr: rate(circuit_breaker_failures_total{name="gotenberg", job="pdf-service"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Circuit Breaker failure rate"
          description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} has high failure rate"
      - alert: NasPdfServiceCircuitBreakerUnhealthy
        expr: circuit_breaker_pod_health{name="gotenberg", job="pdf-service"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Circuit Breaker is Unhealthy"
          description: "Circuit Breaker health check failing for {{ $labels.name }} in pod {{ $labels.pod_name }}"
      - alert: NasPdfServiceCircuitBreakerSlowRecovery
        expr: histogram_quantile(0.95, rate(circuit_breaker_recovery_duration_seconds_bucket{name="gotenberg", job="pdf-service"}[30m])) > 300
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker slow recovery"
          description: "Circuit Breaker for {{ $labels.name }} in pod {{ $labels.pod_name }} is taking too long to recover"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nas-prometheus
  namespace: print-serv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nas-prometheus
  template:
    metadata:
      labels:
        app: nas-prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.enable-lifecycle"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: rules
          mountPath: /etc/prometheus/rules
        - name: storage
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: nas-prometheus-config
      - name: rules
        configMap:
          name: nas-prometheus-rules
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nas-prometheus
  namespace: print-serv
spec:
  selector:
    app: nas-prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP 