apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdf-service.fullname" . }}-templates
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pdf-service.labels" . | nindent 4 }}
binaryData:
  # Храним шаблон DOCX как двоичные данные (base64) для корректного монтирования файла
  template.docx: {{ .Files.Get "files/template.docx" | b64enc }}