apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdf-service.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pdf-service.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "pdf-service.selectorLabels" . | nindent 4 }} 