# Глобальные настройки для тестового окружения
global:
  environment: test
  namespace: print-serv
  
# Имя ресурсов как у существующего стека nas-*
fullnameOverride: nas-pdf-service

# Настройки образа (для RO DevOps реестра используем анонимный pull)
image:
  repository: registry.devops.rgf.local/gimmyhat/pdf-service-go
  pullPolicy: Always

# Отключаем imagePullSecrets в тесте (RO допускает анонимный pull)
imagePullSecrets: []

# Настройки развертывания
deployment:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

# Настройки приложения
app:
  maxConcurrentRequests: 4
  docxTemplate:
    cacheTTL: 5m
  circuitBreaker:
    docx:
      failureThreshold: 5
      resetTimeout: 5s
      halfOpenMaxCalls: 3
      successThreshold: 2
    gotenberg:
      failureThreshold: 5
      resetTimeout: 5s
      halfOpenMaxCalls: 3
      successThreshold: 2
  retry:
    docx:
      maxAttempts: 2
      initialDelay: 50ms
      maxDelay: 200ms
      backoffFactor: 1.5
    gotenberg:
      maxAttempts: 2
      initialDelay: 25ms
      maxDelay: 100ms
      backoffFactor: 1.5

# Настройки PostgreSQL
postgresql:
  enabled: false
  auth:
    database: pdf_service
    username: pdf_service
    password: pdf_service
  primary:
    persistence:
      size: 1Gi

# Настройки мониторинга
prometheus:
  enabled: false
  server:
    persistentVolume:
      size: 4Gi

grafana:
  enabled: false
  persistence:
    enabled: true
    size: 1Gi

jaeger:
  enabled: false
  storage:
    type: memory

# Настройки автомасштабирования
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80