# Глобальные настройки
global:
  environment: test
  namespace: print-serv

# Настройки образа
image:
  repository: registry.devops.rgf.local/gimmyhat/pdf-service-go
  tag: latest
  pullPolicy: Always

# Секреты для pull образов
imagePullSecrets:
  - name: registry-irk-rw

# Настройки развертывания
deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

# Настройки сервиса
service:
  type: NodePort
  port: 8080
  nodePort: 31005

# Настройки приложения
app:
  maxConcurrentRequests: 4
  docxTemplate:
    cacheTTL: 5m
  circuitBreaker:
    docx:
      failureThreshold: 10
      resetTimeout: 10s
      halfOpenMaxCalls: 5
      successThreshold: 3
    gotenberg:
      failureThreshold: 10
      resetTimeout: 10s
      halfOpenMaxCalls: 5
      successThreshold: 3
  retry:
    docx:
      maxAttempts: 2
      initialDelay: 50ms
      maxDelay: 200ms
      backoffFactor: 1.5
    gotenberg:
      maxAttempts: 2
      initialDelay: 25ms
      maxDelay: 100ms
      backoffFactor: 1.5

# Настройки Gotenberg
gotenberg:
  enabled: true
  url: http://nas-pdf-service-gotenberg:3000

# Настройки PostgreSQL
postgresql:
  enabled: true
  auth:
    database: pdf_service
    username: pdf_service
    password: pdf_service
  primary:
    persistence:
      size: 1Gi

# Настройки Prometheus
prometheus:
  enabled: true
  server:
    persistentVolume:
      size: 8Gi

# Настройки Grafana
grafana:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  dashboards:
    default:
      pdf-service-dashboard:
        json: |
          # Здесь будет JSON дашборда

# Настройки Jaeger
jaeger:
  enabled: true
  storage:
    type: memory

# Настройки хранилища
storage:
  tmp:
    sizeLimit: 2Gi
  stats:
    size: 1Gi

# Настройки HPA
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80 