name: Build and Deploy

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  DOCKER_IMAGE: dh-mirror.gitverse.ru/gimmyhat/pdf-service-go
  K8S_NAMESPACE: print-serv

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Update deployment image
        run: |
          # Обновляем тег образа в deployment
          sed -i "s|image: pdf-service-go:latest|image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}|" k8s/nas-pdf-service-deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          # Применяем конфигурации
          kubectl apply -f k8s/nas-pdf-service-configmap.yaml
          kubectl apply -f k8s/nas-pdf-service-templates-configmap.yaml
          kubectl apply -f k8s/nas-pdf-service-gotenberg-deployment.yaml
          kubectl apply -f k8s/nas-pdf-service-deployment.yaml
          kubectl apply -f k8s/nas-pdf-service-hpa.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/nas-pdf-service -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout status deployment/nas-pdf-service-gotenberg -n ${{ env.K8S_NAMESPACE }} 